### ISSUE TITLE
Composing from row doesn't add clearfix

### ISSUE THREAD

**Issue by medeeiros** [cdonohue/css-modules-bootstrap#2]
I'm trying to use your method, however when composing from `row` I don't get the `:before` which acts as a clearfix. Any idea why?

``` css
composes: row from 'bootstrap/less/grid.less';
```

**Comment by cdonohue** [comment]
@GuilhermeMedeiros it looks like it's just not applying the mixin when `.makeRow()` runs in `grid.less`.

In my opinion, if you want to use css modules, you need to either start from scratch and build your own, or find a library that comes with true reusable components (ones that can stand entirely on their own).

This repo was more of an exploration than a solution. Your issue sheds more light on the fact that bootstrap is really an "all or nothing" solution.
